### ISSUE TITLE
"Is MST highlighted" check crashes if edge has no label

### ISSUE THREAD

**Issue by Willem3141** [graphchecker/moodle-qtype_graphchecker#106]
In GitLab by @Willem3141 on Aug 12, 2020, 14:02

```
Traceback (most recent call last):
  File "checkrunner.py", line 35, in run
    result = check_method(graph, **argument)
  File "basic.py", line 72, in mst
    weights = [int(e['label']) for e in student_answer.es]
  File "basic.py", line 72, in 
    weights = [int(e['label']) for e in student_answer.es]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Willem3141** [comment]
In GitLab by @Willem3141 on Aug 12, 2020, 14:03

Same also holds for "Max-heap structure" and "Min-heap structure" with vertices that have no label.

**Comment by Willem3141** [comment]
In GitLab by @Willem3141 on Aug 20, 2020, 10:52

closed
