### ISSUE TITLE
"Degree sequence" check crashes on a graph without edges

### ISSUE THREAD

**Issue by Willem3141** [graphchecker/moodle-qtype_graphchecker#107]
In GitLab by @Willem3141 on Aug 12, 2020, 14:05

I just drew a single vertex and got:

```
Traceback (most recent call last):
  File "checkrunner.py", line 35, in run
    result = check_method(graph, **argument)
  File "degrees.py", line 28, in vertex_degree_sequence
    student_degs.append(v.degree())
UnboundLocalError: local variable 'student_degs' referenced before assignment
```

**Comment by Willem3141** [comment]
In GitLab by @Willem3141 on Aug 20, 2020, 10:52

closed
