### ISSUE TITLE
Isomorphism check crashes for empty sample answer

### ISSUE THREAD

**Issue by Willem3141** [graphchecker/moodle-qtype_graphchecker#35]
In GitLab by @Willem3141 on Feb 26, 2020, 10:58

```
Bad output from grader: 
Traceback (most recent call last):
  File "__tester__.python3", line 24, in <module>
    result = basic.isomorphism(student_answer, sample_answer, preload_answer)
  File "basic.py", line 37, in isomorphism
    g2 = _to_igraph(sample_answer)
  File "basic.py", line 8, in _to_igraph
    for vertex in graph['nodes']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Willem3141** [comment]
In GitLab by @Willem3141 on Feb 26, 2020, 11:02

closed via commit e0bfbccebf1a4c4878c8c9c9713aaa2084867935

 *By Willem Sonke on 2020-02-26T10:02:56 (imported from GitLab project)*
